### ISSUE TITLE
Crash in NotificationAwareCard

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#794]
```
Caused by android.os.TransactionTooLargeException
data parcel size 1367556 bytes
android.os.BinderProxy.transactNative (Binder.java)
arrow_drop_down
android.support.v4.app.NotificationManagerCompat.notify (NotificationManagerCompat.java:194)
arrow_right
de.tum.in.tumcampusapp.component.ui.overview.card.NotificationAwareCard.notifyUser (NotificationAwareCard.kt:58)
de.tum.in.tumcampusapp.component.ui.overview.card.NotificationAwareCard.apply (NotificationAwareCard.kt:81)
de.tum.in.tumcampusapp.component.ui.transportation.TransportController.onRequestCard (TransportController.java:362)
de.tum.in.tumcampusapp.component.ui.overview.CardManager.update (CardManager.java:154)
de.tum.in.tumcampusapp.service.DownloadService.download (DownloadService.java:131)
de.tum.in.tumcampusapp.service.DownloadService.lambda$onHandleWork$0$DownloadService (DownloadService.java:187)
de.tum.in.tumcampusapp.service.DownloadService$$Lambda$0.run (Unknown Source)
java.lang.Thread.run (Thread.java:761)
```

**Comment by saileru** [comment]
I tried to reproduce this crash.
I activated Notifications in Settings-> News
After restarting the app, I encounter a crash

**Comment by saileru** [comment]
I tried to reproduce this crash.
I activated notifictations in Settings->News.
After restarting I encountered a different crash:

E/AndroidRuntime: FATAL EXCEPTION: Thread-1692
                  Process: de.tum.in.tumcampus, PID: 1574
                  java.lang.IllegalArgumentException: Path must not be empty.
                      at com.squareup.picasso.Picasso.load(Picasso.java:332)
                      at de.tum.in.tumcampusapp.component.ui.news.NewsCard.fillNotification(NewsCard.java:112)
                      at de.tum.in.tumcampusapp.component.ui.overview.card.NotificationAwareCard.notifyUser(NotificationAwareCard.kt:53)
                      at de.tum.in.tumcampusapp.component.ui.overview.card.NotificationAwareCard.apply(NotificationAwareCard.kt:81)
                      at de.tum.in.tumcampusapp.component.ui.news.NewsController.onRequestCard(NewsController.java:198)
                      at de.tum.in.tumcampusapp.component.ui.overview.CardManager.update(CardManager.java:154)
                      at de.tum.in.tumcampusapp.service.DownloadService.download(DownloadService.java:131)
                      at de.tum.in.tumcampusapp.service.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:187)
                      at de.tum.in.tumcampusapp.service.DownloadService$$Lambda$0.run(Unknown Source)
                      at java.lang.Thread.run(Thread.java:818)

**Comment by jacqueline8711** [comment]
@saileru the PR I made yesterday (#798) that should fix that other crash. If it prevents you from working on this issue, you can work on the branch ```jacqueline8711/picasso_bugfix``` for now or just check for an empty value yourself and remove that code before making a PR

**Comment by saileru** [comment]
Ah I see, thank you!

**Comment by saileru** [comment]
So far, I was not able to reproduce the TransactionTooLargeException, so it is difficult for me to come up with a fix.
Back to "Next" for now.

**Comment by kordianbruck** [comment]
@thellmund fixed right?

**Comment by thellmund** [comment]
There is no more `NotificationAwareCard` once we merge the intelligent notification scheduling. However, we still use NotificationManagerCompat, so I assume that this bug can still occur. I'll have a look at it within the next week.

**Comment by kordianbruck** [comment]
Will be closed with #879

**Comment by thellmund** [comment]
Still an issue in 1.6.1, as #879 is not added yet. Working on a quick fix in #995 for the next point release.

**Comment by kordianbruck** [comment]
Now merged and released with 1.6.2
